### ISSUE TITLE
(Bug?) multiple calls to $setGlobalVars overwrites

### ISSUE THREAD

**Issue by valgaze** [jstty/beelzebub#13] opened 2016-11-02 19:53 UTC
Calling this.$setGlobalVars(payload) in multiple places overwrites existing globalVars.

Easy fix on the user would be to cache existing before adding new vars, should be documented somewhere

**Comment by jstty** [comment] 2016-11-13 07:31
Not a bug, this is intended behavior. But, yes this should be documented.
Should be resolved in #23

**Closed as completed** 2016-11-13 07:32 UTC
Labels: bug
